### ISSUE TITLE
To make changes in the CONTRIBUTING.md file

### ISSUE THREAD

**Issue by katariyanaman** [faaiz-space/hut-calci#20]
Sir there are some grammatical and spelling mistakes (like contriubutions is contributions) that I want to correct in the CONTRIBUTING.md file, I want to make required changes to the file so can you plz assign this to me.

**Comment by faaiz-space** [comment]
Yeah feel free to submit a PR by creating a new branch we will look and merge soon⭐

**Comment by faaiz-space** [comment]
Respective PR is merged

**Comment by katariyanaman** [comment]
Thank you sir
