### ISSUE TITLE
Enhancing the Readme.md file

### ISSUE THREAD

**Issue by nishkarsh800** [faaiz-space/hut-calci#22]
In this i'm going to add the table of contents : Overview, Project Maintainer, Contributors, Open Source Programs, Feedback.

**Comment by faaiz-space** [comment]
Go forth then 📸 we'll be waiting

**Comment by nishkarsh800** [comment]
Kindly assign me this issue

**Comment by faaiz-space** [comment]
> Kindly assign me this issue

The person created this issue might be working on it, though I can't confirm

**Comment by nishkarsh800** [comment]
@faaiz-space Kindly give label to this issue as "hacktoberfest" as I am a hacktoberfest contributor.
