### ISSUE TITLE
Change the Theme of the Site

### ISSUE THREAD

**Issue by faaiz-space** [faaiz-space/hut-calci#3]
Currently the site is having a purple-white theme.

So change it to a decent colour and which would be having a look of modern site

**Comment by sambhavgupta0705** [comment]
Can you elaborate in what type of colors and theme you want for it

**Comment by sarah-adewale** [comment]
Hello, i will like to work on this. Do you have any specific colors in mind? Can i change the images so that it matches the style i choose?

**Comment by PaceHut** [comment]
> Hello, i will like to work on this. Do you have any specific colors in mind? Can i change the images so that it matches the style i choose?

Yeah you can choose a modern pallette as your liking

**Comment by Nainish-Rai** [comment]
Hey, I want to contribute to this, Please assign me so that i can start working on it

**Comment by faaiz-space** [comment]
> Hey, I want to contribute to this, Please assign me so that i can start working on it

Sorry we forgot to close this issue as this is already fixed

**Comment by faaiz-space** [comment]
Fixed
