### ISSUE TITLE
Add validation to prevent letter input

### ISSUE THREAD

**Issue by MasterReach1** [faaiz-space/hut-calci#33]
I have added regex validation to the calculator input to prevent keyboard letter input. Please assign this issue to me and I will submit a PR

**Comment by faaiz-space** [comment]
> I have added regex validation to the calculator input to prevent keyboard letter input. Please assign this issue to me and I will submit a PR

Yeah @MasterReach1 we are glad to see your effort and we are assigning this issue to you.

Another thing is if you can add the functionality on keypress 'Enter' to evaluate the result which is currently being done only on clicking the "=" sign.

You can raise another issue for it.✅

**Comment by MasterReach1** [comment]
> > I have added regex validation to the calculator input to prevent keyboard letter input. Please assign this issue to me and I will submit a PR
> 
> Yeah @MasterReach1 we are glad to see your effort and we are assigning this issue to you.
> 
> Another thing is if you can add the functionality on keypress 'Enter' to evaluate the result which is currently being done only on clicking the "=" sign.
> 
> You can raise another issue for it.✅

I certainly will. I noticed this feature was lacking and am working on a solution now. Thanks!

**Comment by faaiz-space** [comment]
Respective PR is merged
